### ISSUE TITLE
Functional Conformance Table - Change API Names

### ISSUE THREAD

**Issue by EkkeErick** [OpenBanking-Brasil/conformance#4]
Given that the names of the APIs will be embeded on our website and everything will be in PT-BR i would like to request you to change the presented names from english to portuguese.

This means that:

Consents should become Consentimento
Resources stay as is
Customers (Personal) becomes Dados Cadastrais (PF)
Customers (Business) becomes Dados Cadastrais (PJ)
Credit Cards becomes Cartão de Crédito
Accounts becomes Contas
Credit Operations shall be broken down into 4 Colums:
Operações de Crédito - Empréstimos
Operações de Crédito - Financiamentos
Operações de Crédito - Adiantamento a Depositantes
Operações de Crédito - Direitos Creditórios Descontados

**Comment by OpenBankingBrasil-git** [comment]
@MichaelFraser1999 , the API Registration is still there. We need it removed.
