### ISSUE TITLE
Typo on Table 

### ISSUE THREAD

**Issue by EkkeErick** [OpenBanking-Brasil/conformance#43]
Ágota Correctora de Títulos e Valores Mobiliários S.A

Should be Ágora*

Banco BRG Pactual S.A.

Should be BTG*

**Comment by OpenBankingBrasil-git** [comment]
CAIXA ECONÔMICA FEDERA should be CAIXA ECONÔMICA FEDERAL

Ágota Correctora de Títulos e Valores Mobiliários S.A should be Ágoraa Corretora de Títulos e Valores Mobiliários S.A
